# Generated by architectural refactor.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('servico', models.CharField(max_length=255)),
                ('prazo_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('agendado', 'Agendado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='obras.obra')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['prazo_pagamento'],
            },
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['status_pagamento', 'prazo_pagamento'], name='forn_status_prazo_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['obra', 'prazo_pagamento'], name='forn_obra_prazo_idx'),
        ),
        migrations.AddConstraint(
            model_name='fornecedor',
            constraint=models.CheckConstraint(check=models.Q(('valor__gte', 0)), name='fornecedor_valor_non_negative'),
        ),
    ]
