# Generated by architectural refactor.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_protect_obra_history'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fornecedor',
            table='fornecedores',
        ),
    ]
