# Generated by Django 5.2.12 on 2026-03-06 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('orcamento_aprovado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('custo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('progresso', models.IntegerField(default=0, help_text='Percentagem de progresso (0-100)')),
                ('status', models.CharField(choices=[('em_curso', 'Em Curso'), ('concluida', 'Concluída'), ('suspensa', 'Suspensa'), ('planeada', 'Planeada')], default='planeada', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Obras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PrevisaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(help_text='Ex: Abr 2026', max_length=20)),
                ('recebimentos_previstos', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pagamentos_previstos', models.DecimalField(decimal_places=2, max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Previsões Financeiras',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('servico', models.CharField(max_length=255)),
                ('prazo_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('agendado', 'Agendado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='api.obra')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['prazo_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('categoria', models.CharField(choices=[('clientes', 'Clientes'), ('materiais', 'Materiais'), ('mao_de_obra', 'Mão de Obra'), ('subcontratados', 'Subcontratados'), ('equipamentos', 'Equipamentos'), ('licencas', 'Licenças/Taxas'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='api.obra')),
            ],
            options={
                'verbose_name_plural': 'Transações',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
