# Generated by architectural refactor.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('orcamento_aprovado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('custo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('progresso', models.IntegerField(default=0, help_text='Percentagem de progresso (0-100)')),
                ('status', models.CharField(choices=[('em_curso', 'Em Curso'), ('concluida', 'Concluida'), ('suspensa', 'Suspensa'), ('planeada', 'Planeada')], default='planeada', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Obras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(fields=['status', 'criado_em'], name='obra_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='obra',
            constraint=models.CheckConstraint(check=models.Q(('orcamento_aprovado__gte', 0)), name='obra_orcamento_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='obra',
            constraint=models.CheckConstraint(check=models.Q(('custo_atual__gte', 0)), name='obra_custo_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='obra',
            constraint=models.CheckConstraint(check=models.Q(('progresso__gte', 0), ('progresso__lte', 100)), name='obra_progresso_0_100'),
        ),
        migrations.AddConstraint(
            model_name='obra',
            constraint=models.CheckConstraint(check=models.Q(('data_fim_prevista__isnull', True), ('data_fim_prevista__gte', models.F('data_inicio')), _connector='OR'), name='obra_data_fim_after_inicio'),
        ),
    ]
