# Generated by architectural refactor.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(help_text='Ex: Abr 2026', max_length=20, unique=True)),
                ('recebimentos_previstos', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pagamentos_previstos', models.DecimalField(decimal_places=2, max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Previsoes Financeiras',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('categoria', models.CharField(choices=[('clientes', 'Clientes'), ('materiais', 'Materiais'), ('mao_de_obra', 'Mao de Obra'), ('subcontratados', 'Subcontratados'), ('equipamentos', 'Equipamentos'), ('licencas', 'Licencas/Taxas'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='obras.obra')),
            ],
            options={
                'verbose_name_plural': 'Transacoes',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='previsaofinanceira',
            constraint=models.CheckConstraint(check=models.Q(('recebimentos_previstos__gte', 0)), name='previsao_recebimentos_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='previsaofinanceira',
            constraint=models.CheckConstraint(check=models.Q(('pagamentos_previstos__gte', 0)), name='previsao_pagamentos_non_negative'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['tipo', 'data'], name='trans_tipo_data_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['categoria', 'data'], name='trans_cat_data_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['obra', 'data'], name='trans_obra_data_idx'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.CheckConstraint(check=models.Q(('valor__gte', 0)), name='transacao_valor_non_negative'),
        ),
    ]
