# Generated by architectural refactor.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='obra',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='transacoes',
                to='obras.obra',
            ),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['data'], name='trans_data_idx'),
        ),
    ]
