# Generated by architectural refactor.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_protect_obra_history_and_indexes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transacao',
            table='transacoes',
        ),
        migrations.AlterModelTable(
            name='previsaofinanceira',
            table='previsoes_financeiras',
        ),
    ]
