# Generated by architectural refactor.

from django.db import migrations


LEGACY_TABLES = [
    'legacy_api_notificacao',
    'legacy_api_transacao',
    'legacy_api_previsaofinanceira',
    'legacy_api_fornecedor',
    'legacy_api_obra',
]


def drop_legacy_tables(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        for table_name in LEGACY_TABLES:
            cursor.execute(f'DROP TABLE IF EXISTS "{table_name}"')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_consolidate_legacy_api_tables'),
        ('financeiro', '0003_rename_financeiro_tables'),
        ('fornecedores', '0003_rename_table_fornecedores'),
        ('notificacoes', '0002_rename_table_notificacoes'),
        ('obras', '0002_rename_table_obras'),
    ]

    operations = [
        migrations.RunPython(drop_legacy_tables, migrations.RunPython.noop),
    ]
