# Generated by architectural refactor.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notificacao',
            table='notificacoes',
        ),
    ]
