# Generated by architectural refactor.

import django.db.models.deletion
from django.db import migrations, models


def backfill_sources(apps, schema_editor):
    Notificacao = apps.get_model('notificacoes', 'Notificacao')
    Obra = apps.get_model('obras', 'Obra')
    Fornecedor = apps.get_model('fornecedores', 'Fornecedor')

    valid_ids = []
    for notification in Notificacao.objects.all():
        if notification.origem_tipo == 'obra' and Obra.objects.filter(pk=notification.origem_id).exists():
            notification.obra_id = notification.origem_id
            notification.fornecedor_id = None
            notification.save(update_fields=['obra', 'fornecedor'])
            valid_ids.append(notification.pk)
        elif (
            notification.origem_tipo == 'fornecedor'
            and Fornecedor.objects.filter(pk=notification.origem_id).exists()
        ):
            notification.fornecedor_id = notification.origem_id
            notification.obra_id = None
            notification.save(update_fields=['obra', 'fornecedor'])
            valid_ids.append(notification.pk)

    Notificacao.objects.exclude(pk__in=valid_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_rename_table_obras'),
        ('fornecedores', '0003_rename_table_fornecedores'),
        ('notificacoes', '0002_rename_table_notificacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='fornecedor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notificacoes',
                to='fornecedores.fornecedor',
            ),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='obra',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notificacoes',
                to='obras.obra',
            ),
        ),
        migrations.RunPython(backfill_sources, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='notificacao',
            name='unique_notificacao_origem',
        ),
        migrations.RemoveIndex(
            model_name='notificacao',
            name='notif_origem_idx',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='origem_id',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='origem_tipo',
        ),
        migrations.AddConstraint(
            model_name='notificacao',
            constraint=models.UniqueConstraint(
                condition=models.Q(('obra__isnull', False)),
                fields=('tipo', 'obra'),
                name='unique_notificacao_obra',
            ),
        ),
        migrations.AddConstraint(
            model_name='notificacao',
            constraint=models.UniqueConstraint(
                condition=models.Q(('fornecedor__isnull', False)),
                fields=('tipo', 'fornecedor'),
                name='unique_notificacao_fornecedor',
            ),
        ),
        migrations.AddConstraint(
            model_name='notificacao',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('fornecedor__isnull', True), ('obra__isnull', False)),
                    models.Q(('fornecedor__isnull', False), ('obra__isnull', True)),
                    _connector='OR',
                ),
                name='notificacao_exactly_one_source',
            ),
        ),
    ]
